### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zjzser** [cdjkim/audiocaps#15]
So how does the dataset end up being downloaded?

**Comment by cdjkim** [comment]
Hi,

Looking inside the `dataset` directory, there exist train/validation/test .csv files with columns below:

- audiocap_id: The id unique to the audio clips and their corresponding caption.
- youtube_id: The youtube clip that the audio belongs to. You can use this to obtain the VGGish embedding from AudioSet.
- start_time: The start time of the clip.

You can use the youtube_id and the start time to obtain the audio.

**Comment by zjzser** [comment]
Hello, I want to use Audiocap dataset for another task. I'm wondering how to batch process files like train.csv to get images (videos) from youtube - describing such pairs of files as data, like the files stored by tfrecord? sorry i'm a newbie
&nbsp;


2500859682
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris Dongjoo ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cdjkim/audiocaps] dataset (Issue #15)






嗨

看里面的资料组目录中，存在train/validation/test .csv列在下面的文件：

音频帽_id:音频剪辑及其对应的标题所特有的id。

youtube_id: 音频所属的youtube剪辑。您可以使用此功能从AudioSet获得VGGish嵌入。

start_time：剪辑的开始时间。

您可以使用youtube_id和开始时间来获取音频。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by cdjkim** [comment]
To "batch process" them, it would be in your best interest to look into multi-processing.
 
I am unsure what you mean by "describing such pairs of files as data, like the files stored by tfrecord"!

**Comment by zjzser** [comment]
emmm, because the DataSet dataset( https://research.google.com/audioset/download.html)
It also provides data in CSV format, and also provides data stored in tfrecord that can be used directly... Do you mean that I should manually build multi-processing to grab from youtube.com based on CSV files?

&nbsp;


2500859682
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris Dongjoo ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 晚上6:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cdjkim/audiocaps] dataset (Issue #15)





 
To "batch process" them, it would be in your best interest to look into multi-processing.
 
I am unsure what you mean by "describing such pairs of files as data, like the files stored by tfrecord"!

**Comment by cdjkim** [comment]
If you want to use the tfrecord embeddings from AudioSet, I believe you can also obtain it via the youtube_id in the csv files since AudioCaps was built on top of AudioSet data! 

And for raw audio files, yes that is correct.
