### ISSUE TITLE
Length of clips

### ISSUE THREAD

**Issue by nofreewill42** [cdjkim/audiocaps#20]
There is a column with start_time but no mention of duration. Is duration mentioned in the paper somewhere?

**Comment by nofreewill42** [comment]
I found it, 10 seconds seems to fit well some of audio clips + caption that I checked, then ctrl + f "10 second" in the paper and there it is.

![image](https://github.com/cdjkim/audiocaps/assets/14865017/f3e0b273-129a-49ff-b00e-f656fb565813)

**Comment by daisukelab** [comment]
FYI -- If you have not downloaded the audio files, this repo provides you with an easier way to do that.

https://github.com/XinhaoMei/ACT?tab=readme-ov-file#set-up-dataset

**Comment by cdjkim** [comment]
great! I will close the issue for now!

Also, FYI, we will release the audios for downloading with twice the dataset in the near future!
