### ISSUE TITLE
Request final 115K video ids with word labels

### ISSUE THREAD

**Issue by YapengTian** [cdjkim/audiocaps#3]
Nice work and thanks for sharing the dataset and code!

In your paper, I found that "The final number of audio clips is about 115K, from which we obtain captions for 46K as the first version".  Could you please also share the final dataset with only word labels? Thank you!

Best,
Yapeng

**Comment by cdjkim** [comment]
Hi Yapeng,

Thanks for the interest :)
Our final caption dataset is still undergoing collection, but we hope to release it within a few months' time. 
But if I understood you correctly, "only word labels" are required, these can be obtained from the original [AudioSet](https://research.google.com/audioset/dataset/index.html)!

Chris
