### ISSUE TITLE
Is the duration of each audio clip in AudioCaps 10 seconds?

### ISSUE THREAD

**Issue by LittleFlyingSheep** [cdjkim/audiocaps#7]
Hi, I want to download the audio data of AudioCaps, and writting to notarize the duration of audio clips. In the csv files, just beginning time is provided.  Is the duration of each audio clip in AudioCaps 10 seconds?

**Comment by cdjkim** [comment]
Hi,
That is correct. As AudioCaps is a subset of Audioset, the duration of the audio is the same as stated [here](research.google.com/audioset). 

Best,
