### ISSUE TITLE
How to Download AudioCaps

### ISSUE THREAD

**Issue by felixkreuk** [cdjkim/audiocaps#9]
Hi,

Thanks so much for this great and impressive resource!
I am relatively new to the field of audio captioning, so apologies if my question is basic :)
I was wondering if you have a piece of code to download the relevant files?
Or do I need to download the entire AudioSet data? If so, can you please point me to a code that does that reliably?

Thanks in advance,
Felix

**Comment by cdjkim** [comment]
Hi Felix,

Although you can download the entire AudioSet data and filter out the necessary parts through the youtube_ids (take a look at the test, val, train csvs released), you can similarly download the select audios through the youtube_ids as well.
As per the last question, this [link](https://github.com/ytdl-org/youtube-dl) may be of good use.

Chris

**Comment by felixkreuk** [comment]
Thanks you!
